version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:12
    restart: always
    working_dir: /usr/src/esk-clean-ts-api-v02
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/esk-clean-ts-api-v02
    volumes:
      - ./dist/:/usr/src/esk-clean-node-api/dist/
      - ./package.json:/usr/src/esk-clean-ts-api-v2/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo